/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CarDamageUploader {
    }
}
declare global {
    interface HTMLCarDamageUploaderElement extends Components.CarDamageUploader, HTMLStencilElement {
    }
    var HTMLCarDamageUploaderElement: {
        prototype: HTMLCarDamageUploaderElement;
        new (): HTMLCarDamageUploaderElement;
    };
    interface HTMLElementTagNameMap {
        "car-damage-uploader": HTMLCarDamageUploaderElement;
    }
}
declare namespace LocalJSX {
    interface CarDamageUploader {
    }
    interface IntrinsicElements {
        "car-damage-uploader": CarDamageUploader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "car-damage-uploader": LocalJSX.CarDamageUploader & JSXBase.HTMLAttributes<HTMLCarDamageUploaderElement>;
        }
    }
}
